export const TYPES = {
  Orchestrator: Symbol.for('Orchestrator'),
  ServerID: Symbol.for('Server ID'),
  ProvisionURL: Symbol.for('Provision URL'),
  EmailAddress: Symbol.for('Email address'),
  UploadUser: Symbol.for('Upload User'),
  UploadPassword: Symbol.for('Upload Password'),
  FormDataManager: Symbol.for('Form Data Manager'),
  ProvisioningService: Symbol.for('Provision Service'),
  StorageService: Symbol.for('Storage Service'),
  ScreenshotService: Symbol.for('Screenshot Service'),
  ChunkToScroll: Symbol.for('Chunk To Scroll'),
  ScreenshotHeight: Symbol.for('Screenshot Height'),
  WindowWidth: Symbol.for('Window Width'),
  TopMostScrollPosition: Symbol.for('Top-most scroll position'),
  ScreenshotDir: Symbol.for('Screenshot Directory'),
  ScreenshotBuilder: Symbol.for('Screenshot Builder'),
  GuidRegex: Symbol.for('Guid Regex'),
  EmlPath: Symbol.for('Eml Path'),
  EmlManager: Symbol.for('Eml Manager'),
  AwsRegion: Symbol.for('AWS Region'),
  AwsAcl: Symbol.for('AWS ACL'),
  AwsContentEncoding: Symbol.for('AWS Content Encoding'),
  AwsStorageClass: Symbol.for('AWS Storage Class'),
  AppleScriptManager: Symbol.for('AppleScript Manager'),
  Watcher: Symbol.for('Watcher'),
  GuidManager: Symbol.for('Guid Manager'),
  TestProcessor: Symbol.for('TestProcessor'),
};
